on: [push]

jobs:
  test_is-valid-json-action:
    runs-on: ubuntu-latest
    name: A job to test whether the is-valid-json is working properly
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: get-version-from-package-json
        uses: ./ # Uses an action in the root directory
        id: get-version-from-package-json
        with:
          get-version-from-package-json : './test-data/package.json'
      - name: print-validity
        run: echo "The version key in your json was ${{ steps.get-version-from-package-json.outputs.version }}"
     